package vamservice.Pojo.JAVA; /**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class obfuscatedids_value extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6641867395876796974L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\n" +
          "\t\"type\": \"record\",\n" +
          "\t\"name\": \"obfuscatedids_value\",\n" +
          "\t\"fields\": [{\n" +
          "\t\t\"name\": \"profileid\",\n" +
          "\t\t\"type\": \"string\"\n" +
          "\t}, {\n" +
          "\t\t\"name\": \"partyid\",\n" +
          "\t\t\"type\": \"string\"\n" +
          "\t}]\n" +
          "}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<obfuscatedids_value> ENCODER =
      new BinaryMessageEncoder<obfuscatedids_value>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<obfuscatedids_value> DECODER =
      new BinaryMessageDecoder<obfuscatedids_value>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<obfuscatedids_value> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<obfuscatedids_value> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<obfuscatedids_value> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<obfuscatedids_value>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this obfuscatedids_value to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a obfuscatedids_value from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a obfuscatedids_value instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static obfuscatedids_value fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence profileid;
   private java.lang.CharSequence partyid;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public obfuscatedids_value() {}

  /**
   * All-args constructor.
   * @param profileid The new value for profileid
   * @param partyid The new value for partyid
   */
  public obfuscatedids_value(java.lang.CharSequence profileid, java.lang.CharSequence partyid) {
    this.profileid = profileid;
    this.partyid = partyid;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return profileid;
    case 1: return partyid;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: profileid = (java.lang.CharSequence)value$; break;
    case 1: partyid = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'profileid' field.
   * @return The value of the 'profileid' field.
   */
  public java.lang.CharSequence getProfileid() {
    return profileid;
  }


  /**
   * Sets the value of the 'profileid' field.
   * @param value the value to set.
   */
  public void setProfileid(java.lang.CharSequence value) {
    this.profileid = value;
  }

  /**
   * Gets the value of the 'partyid' field.
   * @return The value of the 'partyid' field.
   */
  public java.lang.CharSequence getPartyid() {
    return partyid;
  }


  /**
   * Sets the value of the 'partyid' field.
   * @param value the value to set.
   */
  public void setPartyid(java.lang.CharSequence value) {
    this.partyid = value;
  }

  /**
   * Creates a new obfuscatedids_value RecordBuilder.
   * @return A new obfuscatedids_value RecordBuilder
   */
  public static obfuscatedids_value.Builder newBuilder() {
    return new obfuscatedids_value.Builder();
  }

  /**
   * Creates a new obfuscatedids_value RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new obfuscatedids_value RecordBuilder
   */
  public static obfuscatedids_value.Builder newBuilder(obfuscatedids_value.Builder other) {
    if (other == null) {
      return new obfuscatedids_value.Builder();
    } else {
      return new obfuscatedids_value.Builder(other);
    }
  }

  /**
   * Creates a new obfuscatedids_value RecordBuilder by copying an existing obfuscatedids_value instance.
   * @param other The existing instance to copy.
   * @return A new obfuscatedids_value RecordBuilder
   */
  public static obfuscatedids_value.Builder newBuilder(obfuscatedids_value other) {
    if (other == null) {
      return new obfuscatedids_value.Builder();
    } else {
      return new obfuscatedids_value.Builder(other);
    }
  }

  /**
   * RecordBuilder for obfuscatedids_value instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<obfuscatedids_value>
    implements org.apache.avro.data.RecordBuilder<obfuscatedids_value> {

    private java.lang.CharSequence profileid;
    private java.lang.CharSequence partyid;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(obfuscatedids_value.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.profileid)) {
        this.profileid = data().deepCopy(fields()[0].schema(), other.profileid);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.partyid)) {
        this.partyid = data().deepCopy(fields()[1].schema(), other.partyid);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing obfuscatedids_value instance
     * @param other The existing instance to copy.
     */
    private Builder(obfuscatedids_value other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.profileid)) {
        this.profileid = data().deepCopy(fields()[0].schema(), other.profileid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.partyid)) {
        this.partyid = data().deepCopy(fields()[1].schema(), other.partyid);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'profileid' field.
      * @return The value.
      */
    public java.lang.CharSequence getProfileid() {
      return profileid;
    }


    /**
      * Sets the value of the 'profileid' field.
      * @param value The value of 'profileid'.
      * @return This builder.
      */
    public obfuscatedids_value.Builder setProfileid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.profileid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'profileid' field has been set.
      * @return True if the 'profileid' field has been set, false otherwise.
      */
    public boolean hasProfileid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'profileid' field.
      * @return This builder.
      */
    public obfuscatedids_value.Builder clearProfileid() {
      profileid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'partyid' field.
      * @return The value.
      */
    public java.lang.CharSequence getPartyid() {
      return partyid;
    }


    /**
      * Sets the value of the 'partyid' field.
      * @param value The value of 'partyid'.
      * @return This builder.
      */
    public obfuscatedids_value.Builder setPartyid(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.partyid = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'partyid' field has been set.
      * @return True if the 'partyid' field has been set, false otherwise.
      */
    public boolean hasPartyid() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'partyid' field.
      * @return This builder.
      */
    public obfuscatedids_value.Builder clearPartyid() {
      partyid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public obfuscatedids_value build() {
      try {
        obfuscatedids_value record = new obfuscatedids_value();
        record.profileid = fieldSetFlags()[0] ? this.profileid : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.partyid = fieldSetFlags()[1] ? this.partyid : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<obfuscatedids_value>
    WRITER$ = (org.apache.avro.io.DatumWriter<obfuscatedids_value>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<obfuscatedids_value>
    READER$ = (org.apache.avro.io.DatumReader<obfuscatedids_value>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.profileid);

    out.writeString(this.partyid);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.profileid = in.readString(this.profileid instanceof Utf8 ? (Utf8)this.profileid : null);

      this.partyid = in.readString(this.partyid instanceof Utf8 ? (Utf8)this.partyid : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.profileid = in.readString(this.profileid instanceof Utf8 ? (Utf8)this.profileid : null);
          break;

        case 1:
          this.partyid = in.readString(this.partyid instanceof Utf8 ? (Utf8)this.partyid : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










