package vamservice.Pojo.JAVA; /**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OogwayProfileCreated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -784153124702007696L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\n" +
          "\t\"type\": \"record\",\n" +
          "\t\"name\": \"OogwayProfileCreated\",\n" +
          "\t\"fields\": [{\n" +
          "\t\t\"name\": \"origin\",\n" +
          "\t\t\"type\": \"string\"\n" +
          "\t}, {\n" +
          "\t\t\"name\": \"activityType\",\n" +
          "\t\t\"type\": \"string\"\n" +
          "\t}, {\n" +
          "\t\t\"name\": \"event\",\n" +
          "\t\t\"type\": \"string\"\n" +
          "\t}, {\n" +
          "\t\t\"name\": \"householdId\",\n" +
          "\t\t\"type\": \"string\"\n" +
          "\t}, {\n" +
          "\t\t\"name\": \"originatingSystem\",\n" +
          "\t\t\"type\": \"string\"\n" +
          "\t}, {\n" +
          "\t\t\"name\": \"provider\",\n" +
          "\t\t\"type\": \"string\"\n" +
          "\t}, {\n" +
          "\t\t\"name\": \"proposition\",\n" +
          "\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t}, {\n" +
          "\t\t\"name\": \"activityTimestamp\",\n" +
          "\t\t\"type\": \"string\"\n" +
          "\t}, {\n" +
          "\t\t\"name\": \"profileId\",\n" +
          "\t\t\"type\": \"string\"\n" +
          "\t}, {\n" +
          "\t\t\"name\": \"providerTerritory\",\n" +
          "\t\t\"type\": \"string\"\n" +
          "\t}, {\n" +
          "\t\t\"name\": \"data\",\n" +
          "\t\t\"type\": {\n" +
          "\t\t\t\"type\": \"record\",\n" +
          "\t\t\t\"name\": \"data\",\n" +
          "\t\t\t\"fields\": [{\n" +
          "\t\t\t\t\"name\": \"profile\",\n" +
          "\t\t\t\t\"type\": {\n" +
          "\t\t\t\t\t\"type\": \"record\",\n" +
          "\t\t\t\t\t\"name\": \"profile\",\n" +
          "\t\t\t\t\t\"fields\": [{\n" +
          "\t\t\t\t\t\t\"name\": \"username\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"targetedoptin\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"boolean\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"trackingid\",\n" +
          "\t\t\t\t\t\t\"type\": \"string\"\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"firstname\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"title\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"emailverified\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"boolean\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"targetedoptindate\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"services\",\n" +
          "\t\t\t\t\t\t\"type\": {\n" +
          "\t\t\t\t\t\t\t\"type\": \"map\",\n" +
          "\t\t\t\t\t\t\t\"values\": {\n" +
          "\t\t\t\t\t\t\t\t\"type\": \"record\",\n" +
          "\t\t\t\t\t\t\t\t\"name\": \"services_value\",\n" +
          "\t\t\t\t\t\t\t\t\"fields\": [{\n" +
          "\t\t\t\t\t\t\t\t\t\"name\": \"start\",\n" +
          "\t\t\t\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\t\t\t\"name\": \"end\",\n" +
          "\t\t\t\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\t\t\t\"name\": \"globalaccess\",\n" +
          "\t\t\t\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\t\t\t\"name\": \"mailbox\",\n" +
          "\t\t\t\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\t\t\t\"name\": \"name\",\n" +
          "\t\t\t\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\t\t\t\"name\": \"suspended\",\n" +
          "\t\t\t\t\t\t\t\t\t\"type\": [\"null\", \"boolean\"]\n" +
          "\t\t\t\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\t\t\t\"name\": \"fullysignedup\",\n" +
          "\t\t\t\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t\t\t\t}]\n" +
          "\t\t\t\t\t\t\t}\n" +
          "\t\t\t\t\t\t}\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"mobilenumber\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"targetedoptoutdate\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"hhuserauthorised\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"dateofbirth\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"hhid\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"mobilenumberverified\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"boolean\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"displayname\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"securityquestionid\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"mobilenumberchanged\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"long\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"skyoptin\",\n" +
          "\t\t\t\t\t\t\"type\": \"boolean\"\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"email\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"contactemail\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"emailchanged\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"euportability\",\n" +
          "\t\t\t\t\t\t\"type\": \"boolean\"\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"hhusertype\",\n" +
          "\t\t\t\t\t\t\"type\": \"string\"\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"lastname\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"termsandconditionsaccepted\",\n" +
          "\t\t\t\t\t\t\"type\": \"boolean\"\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"nsprofileid\",\n" +
          "\t\t\t\t\t\t\"type\": \"string\"\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"passwordrequireschange\",\n" +
          "\t\t\t\t\t\t\"type\": [\"null\", \"boolean\"]\n" +
          "\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\"name\": \"registrationdate\",\n" +
          "\t\t\t\t\t\t\"type\": \"string\"\n" +
          "\t\t\t\t\t}]\n" +
          "\t\t\t\t}\n" +
          "\t\t\t}, {\n" +
          "\t\t\t\t\"name\": \"singleusetoken\",\n" +
          "\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t}, {\n" +
          "\t\t\t\t\"name\": \"servicename\",\n" +
          "\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t}, {\n" +
          "\t\t\t\t\"name\": \"contexturl\",\n" +
          "\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t}, {\n" +
          "\t\t\t\t\"name\": \"operatorreference\",\n" +
          "\t\t\t\t\"type\": [\"null\", \"string\"]\n" +
          "\t\t\t}, {\n" +
          "\t\t\t\t\"name\": \"obfuscatedids\",\n" +
          "\t\t\t\t\"type\": {\n" +
          "\t\t\t\t\t\"type\": \"map\",\n" +
          "\t\t\t\t\t\"values\": {\n" +
          "\t\t\t\t\t\t\"type\": \"record\",\n" +
          "\t\t\t\t\t\t\"name\": \"obfuscatedids_value\",\n" +
          "\t\t\t\t\t\t\"fields\": [{\n" +
          "\t\t\t\t\t\t\t\"name\": \"profileid\",\n" +
          "\t\t\t\t\t\t\t\"type\": \"string\"\n" +
          "\t\t\t\t\t\t}, {\n" +
          "\t\t\t\t\t\t\t\"name\": \"partyid\",\n" +
          "\t\t\t\t\t\t\t\"type\": \"string\"\n" +
          "\t\t\t\t\t\t}]\n" +
          "\t\t\t\t\t}\n" +
          "\t\t\t\t}\n" +
          "\t\t\t}]\n" +
          "\t\t}\n" +
          "\t}, {\n" +
          "\t\t\"name\": \"id\",\n" +
          "\t\t\"type\": \"string\"\n" +
          "\t}]\n" +
          "}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OogwayProfileCreated> ENCODER =
      new BinaryMessageEncoder<OogwayProfileCreated>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OogwayProfileCreated> DECODER =
      new BinaryMessageDecoder<OogwayProfileCreated>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OogwayProfileCreated> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OogwayProfileCreated> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OogwayProfileCreated> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OogwayProfileCreated>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OogwayProfileCreated to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OogwayProfileCreated from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OogwayProfileCreated instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OogwayProfileCreated fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence origin;
   private java.lang.CharSequence activityType;
   private java.lang.CharSequence event;
   private java.lang.CharSequence householdId;
   private java.lang.CharSequence originatingSystem;
   private java.lang.CharSequence provider;
   private java.lang.CharSequence proposition;
   private java.lang.CharSequence activityTimestamp;
   private java.lang.CharSequence profileId;
   private java.lang.CharSequence providerTerritory;
   private data data;
   private java.lang.CharSequence id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OogwayProfileCreated() {}

  /**
   * All-args constructor.
   * @param origin The new value for origin
   * @param activityType The new value for activityType
   * @param event The new value for event
   * @param householdId The new value for householdId
   * @param originatingSystem The new value for originatingSystem
   * @param provider The new value for provider
   * @param proposition The new value for proposition
   * @param activityTimestamp The new value for activityTimestamp
   * @param profileId The new value for profileId
   * @param providerTerritory The new value for providerTerritory
   * @param data The new value for data
   * @param id The new value for id
   */
  public OogwayProfileCreated(java.lang.CharSequence origin, java.lang.CharSequence activityType, java.lang.CharSequence event, java.lang.CharSequence householdId, java.lang.CharSequence originatingSystem, java.lang.CharSequence provider, java.lang.CharSequence proposition, java.lang.CharSequence activityTimestamp, java.lang.CharSequence profileId, java.lang.CharSequence providerTerritory, data data, java.lang.CharSequence id) {
    this.origin = origin;
    this.activityType = activityType;
    this.event = event;
    this.householdId = householdId;
    this.originatingSystem = originatingSystem;
    this.provider = provider;
    this.proposition = proposition;
    this.activityTimestamp = activityTimestamp;
    this.profileId = profileId;
    this.providerTerritory = providerTerritory;
    this.data = data;
    this.id = id;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return origin;
    case 1: return activityType;
    case 2: return event;
    case 3: return householdId;
    case 4: return originatingSystem;
    case 5: return provider;
    case 6: return proposition;
    case 7: return activityTimestamp;
    case 8: return profileId;
    case 9: return providerTerritory;
    case 10: return data;
    case 11: return id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: origin = (java.lang.CharSequence)value$; break;
    case 1: activityType = (java.lang.CharSequence)value$; break;
    case 2: event = (java.lang.CharSequence)value$; break;
    case 3: householdId = (java.lang.CharSequence)value$; break;
    case 4: originatingSystem = (java.lang.CharSequence)value$; break;
    case 5: provider = (java.lang.CharSequence)value$; break;
    case 6: proposition = (java.lang.CharSequence)value$; break;
    case 7: activityTimestamp = (java.lang.CharSequence)value$; break;
    case 8: profileId = (java.lang.CharSequence)value$; break;
    case 9: providerTerritory = (java.lang.CharSequence)value$; break;
    case 10: data = (data)value$; break;
    case 11: id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'origin' field.
   * @return The value of the 'origin' field.
   */
  public java.lang.CharSequence getOrigin() {
    return origin;
  }


  /**
   * Sets the value of the 'origin' field.
   * @param value the value to set.
   */
  public void setOrigin(java.lang.CharSequence value) {
    this.origin = value;
  }

  /**
   * Gets the value of the 'activityType' field.
   * @return The value of the 'activityType' field.
   */
  public java.lang.CharSequence getActivityType() {
    return activityType;
  }


  /**
   * Sets the value of the 'activityType' field.
   * @param value the value to set.
   */
  public void setActivityType(java.lang.CharSequence value) {
    this.activityType = value;
  }

  /**
   * Gets the value of the 'event' field.
   * @return The value of the 'event' field.
   */
  public java.lang.CharSequence getEvent() {
    return event;
  }


  /**
   * Sets the value of the 'event' field.
   * @param value the value to set.
   */
  public void setEvent(java.lang.CharSequence value) {
    this.event = value;
  }

  /**
   * Gets the value of the 'householdId' field.
   * @return The value of the 'householdId' field.
   */
  public java.lang.CharSequence getHouseholdId() {
    return householdId;
  }


  /**
   * Sets the value of the 'householdId' field.
   * @param value the value to set.
   */
  public void setHouseholdId(java.lang.CharSequence value) {
    this.householdId = value;
  }

  /**
   * Gets the value of the 'originatingSystem' field.
   * @return The value of the 'originatingSystem' field.
   */
  public java.lang.CharSequence getOriginatingSystem() {
    return originatingSystem;
  }


  /**
   * Sets the value of the 'originatingSystem' field.
   * @param value the value to set.
   */
  public void setOriginatingSystem(java.lang.CharSequence value) {
    this.originatingSystem = value;
  }

  /**
   * Gets the value of the 'provider' field.
   * @return The value of the 'provider' field.
   */
  public java.lang.CharSequence getProvider() {
    return provider;
  }


  /**
   * Sets the value of the 'provider' field.
   * @param value the value to set.
   */
  public void setProvider(java.lang.CharSequence value) {
    this.provider = value;
  }

  /**
   * Gets the value of the 'proposition' field.
   * @return The value of the 'proposition' field.
   */
  public java.lang.CharSequence getProposition() {
    return proposition;
  }


  /**
   * Sets the value of the 'proposition' field.
   * @param value the value to set.
   */
  public void setProposition(java.lang.CharSequence value) {
    this.proposition = value;
  }

  /**
   * Gets the value of the 'activityTimestamp' field.
   * @return The value of the 'activityTimestamp' field.
   */
  public java.lang.CharSequence getActivityTimestamp() {
    return activityTimestamp;
  }


  /**
   * Sets the value of the 'activityTimestamp' field.
   * @param value the value to set.
   */
  public void setActivityTimestamp(java.lang.CharSequence value) {
    this.activityTimestamp = value;
  }

  /**
   * Gets the value of the 'profileId' field.
   * @return The value of the 'profileId' field.
   */
  public java.lang.CharSequence getProfileId() {
    return profileId;
  }


  /**
   * Sets the value of the 'profileId' field.
   * @param value the value to set.
   */
  public void setProfileId(java.lang.CharSequence value) {
    this.profileId = value;
  }

  /**
   * Gets the value of the 'providerTerritory' field.
   * @return The value of the 'providerTerritory' field.
   */
  public java.lang.CharSequence getProviderTerritory() {
    return providerTerritory;
  }


  /**
   * Sets the value of the 'providerTerritory' field.
   * @param value the value to set.
   */
  public void setProviderTerritory(java.lang.CharSequence value) {
    this.providerTerritory = value;
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public data getData() {
    return data;
  }


  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(data value) {
    this.data = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Creates a new OogwayProfileCreated RecordBuilder.
   * @return A new OogwayProfileCreated RecordBuilder
   */
  public static OogwayProfileCreated.Builder newBuilder() {
    return new OogwayProfileCreated.Builder();
  }

  /**
   * Creates a new OogwayProfileCreated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OogwayProfileCreated RecordBuilder
   */
  public static OogwayProfileCreated.Builder newBuilder(OogwayProfileCreated.Builder other) {
    if (other == null) {
      return new OogwayProfileCreated.Builder();
    } else {
      return new OogwayProfileCreated.Builder(other);
    }
  }

  /**
   * Creates a new OogwayProfileCreated RecordBuilder by copying an existing OogwayProfileCreated instance.
   * @param other The existing instance to copy.
   * @return A new OogwayProfileCreated RecordBuilder
   */
  public static OogwayProfileCreated.Builder newBuilder(OogwayProfileCreated other) {
    if (other == null) {
      return new OogwayProfileCreated.Builder();
    } else {
      return new OogwayProfileCreated.Builder(other);
    }
  }

  /**
   * RecordBuilder for OogwayProfileCreated instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OogwayProfileCreated>
    implements org.apache.avro.data.RecordBuilder<OogwayProfileCreated> {

    private java.lang.CharSequence origin;
    private java.lang.CharSequence activityType;
    private java.lang.CharSequence event;
    private java.lang.CharSequence householdId;
    private java.lang.CharSequence originatingSystem;
    private java.lang.CharSequence provider;
    private java.lang.CharSequence proposition;
    private java.lang.CharSequence activityTimestamp;
    private java.lang.CharSequence profileId;
    private java.lang.CharSequence providerTerritory;
    private data data;
    private data.Builder dataBuilder;
    private java.lang.CharSequence id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(OogwayProfileCreated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.origin)) {
        this.origin = data().deepCopy(fields()[0].schema(), other.origin);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.activityType)) {
        this.activityType = data().deepCopy(fields()[1].schema(), other.activityType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.event)) {
        this.event = data().deepCopy(fields()[2].schema(), other.event);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.householdId)) {
        this.householdId = data().deepCopy(fields()[3].schema(), other.householdId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.originatingSystem)) {
        this.originatingSystem = data().deepCopy(fields()[4].schema(), other.originatingSystem);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.provider)) {
        this.provider = data().deepCopy(fields()[5].schema(), other.provider);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.proposition)) {
        this.proposition = data().deepCopy(fields()[6].schema(), other.proposition);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.activityTimestamp)) {
        this.activityTimestamp = data().deepCopy(fields()[7].schema(), other.activityTimestamp);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.profileId)) {
        this.profileId = data().deepCopy(fields()[8].schema(), other.profileId);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.providerTerritory)) {
        this.providerTerritory = data().deepCopy(fields()[9].schema(), other.providerTerritory);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.data)) {
        this.data = data().deepCopy(fields()[10].schema(), other.data);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (other.hasDataBuilder()) {
        this.dataBuilder = data.newBuilder(other.getDataBuilder());
      }
      if (isValidValue(fields()[11], other.id)) {
        this.id = data().deepCopy(fields()[11].schema(), other.id);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
    }

    /**
     * Creates a Builder by copying an existing OogwayProfileCreated instance
     * @param other The existing instance to copy.
     */
    private Builder(OogwayProfileCreated other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.origin)) {
        this.origin = data().deepCopy(fields()[0].schema(), other.origin);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.activityType)) {
        this.activityType = data().deepCopy(fields()[1].schema(), other.activityType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.event)) {
        this.event = data().deepCopy(fields()[2].schema(), other.event);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.householdId)) {
        this.householdId = data().deepCopy(fields()[3].schema(), other.householdId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.originatingSystem)) {
        this.originatingSystem = data().deepCopy(fields()[4].schema(), other.originatingSystem);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.provider)) {
        this.provider = data().deepCopy(fields()[5].schema(), other.provider);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.proposition)) {
        this.proposition = data().deepCopy(fields()[6].schema(), other.proposition);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.activityTimestamp)) {
        this.activityTimestamp = data().deepCopy(fields()[7].schema(), other.activityTimestamp);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.profileId)) {
        this.profileId = data().deepCopy(fields()[8].schema(), other.profileId);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.providerTerritory)) {
        this.providerTerritory = data().deepCopy(fields()[9].schema(), other.providerTerritory);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.data)) {
        this.data = data().deepCopy(fields()[10].schema(), other.data);
        fieldSetFlags()[10] = true;
      }
      this.dataBuilder = null;
      if (isValidValue(fields()[11], other.id)) {
        this.id = data().deepCopy(fields()[11].schema(), other.id);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'origin' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrigin() {
      return origin;
    }


    /**
      * Sets the value of the 'origin' field.
      * @param value The value of 'origin'.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder setOrigin(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.origin = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'origin' field has been set.
      * @return True if the 'origin' field has been set, false otherwise.
      */
    public boolean hasOrigin() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'origin' field.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder clearOrigin() {
      origin = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'activityType' field.
      * @return The value.
      */
    public java.lang.CharSequence getActivityType() {
      return activityType;
    }


    /**
      * Sets the value of the 'activityType' field.
      * @param value The value of 'activityType'.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder setActivityType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.activityType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'activityType' field has been set.
      * @return True if the 'activityType' field has been set, false otherwise.
      */
    public boolean hasActivityType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'activityType' field.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder clearActivityType() {
      activityType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'event' field.
      * @return The value.
      */
    public java.lang.CharSequence getEvent() {
      return event;
    }


    /**
      * Sets the value of the 'event' field.
      * @param value The value of 'event'.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder setEvent(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.event = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'event' field has been set.
      * @return True if the 'event' field has been set, false otherwise.
      */
    public boolean hasEvent() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'event' field.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder clearEvent() {
      event = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'householdId' field.
      * @return The value.
      */
    public java.lang.CharSequence getHouseholdId() {
      return householdId;
    }


    /**
      * Sets the value of the 'householdId' field.
      * @param value The value of 'householdId'.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder setHouseholdId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.householdId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'householdId' field has been set.
      * @return True if the 'householdId' field has been set, false otherwise.
      */
    public boolean hasHouseholdId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'householdId' field.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder clearHouseholdId() {
      householdId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'originatingSystem' field.
      * @return The value.
      */
    public java.lang.CharSequence getOriginatingSystem() {
      return originatingSystem;
    }


    /**
      * Sets the value of the 'originatingSystem' field.
      * @param value The value of 'originatingSystem'.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder setOriginatingSystem(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.originatingSystem = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'originatingSystem' field has been set.
      * @return True if the 'originatingSystem' field has been set, false otherwise.
      */
    public boolean hasOriginatingSystem() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'originatingSystem' field.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder clearOriginatingSystem() {
      originatingSystem = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'provider' field.
      * @return The value.
      */
    public java.lang.CharSequence getProvider() {
      return provider;
    }


    /**
      * Sets the value of the 'provider' field.
      * @param value The value of 'provider'.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder setProvider(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.provider = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'provider' field has been set.
      * @return True if the 'provider' field has been set, false otherwise.
      */
    public boolean hasProvider() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'provider' field.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder clearProvider() {
      provider = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'proposition' field.
      * @return The value.
      */
    public java.lang.CharSequence getProposition() {
      return proposition;
    }


    /**
      * Sets the value of the 'proposition' field.
      * @param value The value of 'proposition'.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder setProposition(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.proposition = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'proposition' field has been set.
      * @return True if the 'proposition' field has been set, false otherwise.
      */
    public boolean hasProposition() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'proposition' field.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder clearProposition() {
      proposition = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'activityTimestamp' field.
      * @return The value.
      */
    public java.lang.CharSequence getActivityTimestamp() {
      return activityTimestamp;
    }


    /**
      * Sets the value of the 'activityTimestamp' field.
      * @param value The value of 'activityTimestamp'.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder setActivityTimestamp(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.activityTimestamp = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'activityTimestamp' field has been set.
      * @return True if the 'activityTimestamp' field has been set, false otherwise.
      */
    public boolean hasActivityTimestamp() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'activityTimestamp' field.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder clearActivityTimestamp() {
      activityTimestamp = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'profileId' field.
      * @return The value.
      */
    public java.lang.CharSequence getProfileId() {
      return profileId;
    }


    /**
      * Sets the value of the 'profileId' field.
      * @param value The value of 'profileId'.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder setProfileId(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.profileId = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'profileId' field has been set.
      * @return True if the 'profileId' field has been set, false otherwise.
      */
    public boolean hasProfileId() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'profileId' field.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder clearProfileId() {
      profileId = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'providerTerritory' field.
      * @return The value.
      */
    public java.lang.CharSequence getProviderTerritory() {
      return providerTerritory;
    }


    /**
      * Sets the value of the 'providerTerritory' field.
      * @param value The value of 'providerTerritory'.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder setProviderTerritory(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.providerTerritory = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'providerTerritory' field has been set.
      * @return True if the 'providerTerritory' field has been set, false otherwise.
      */
    public boolean hasProviderTerritory() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'providerTerritory' field.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder clearProviderTerritory() {
      providerTerritory = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public data getData() {
      return data;
    }


    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder setData(data value) {
      validate(fields()[10], value);
      this.dataBuilder = null;
      this.data = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[10];
    }

    /**
     * Gets the Builder instance for the 'data' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public data.Builder getDataBuilder() {
      if (dataBuilder == null) {
        if (hasData()) {
          setDataBuilder(data.newBuilder(data));
        } else {
          setDataBuilder(data.newBuilder());
        }
      }
      return dataBuilder;
    }

    /**
     * Sets the Builder instance for the 'data' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public OogwayProfileCreated.Builder setDataBuilder(data.Builder value) {
      clearData();
      dataBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'data' field has an active Builder instance
     * @return True if the 'data' field has an active Builder instance
     */
    public boolean hasDataBuilder() {
      return dataBuilder != null;
    }

    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder clearData() {
      data = null;
      dataBuilder = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder setId(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.id = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public OogwayProfileCreated.Builder clearId() {
      id = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OogwayProfileCreated build() {
      try {
        OogwayProfileCreated record = new OogwayProfileCreated();
        record.origin = fieldSetFlags()[0] ? this.origin : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.activityType = fieldSetFlags()[1] ? this.activityType : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.event = fieldSetFlags()[2] ? this.event : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.householdId = fieldSetFlags()[3] ? this.householdId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.originatingSystem = fieldSetFlags()[4] ? this.originatingSystem : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.provider = fieldSetFlags()[5] ? this.provider : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.proposition = fieldSetFlags()[6] ? this.proposition : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.activityTimestamp = fieldSetFlags()[7] ? this.activityTimestamp : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.profileId = fieldSetFlags()[8] ? this.profileId : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.providerTerritory = fieldSetFlags()[9] ? this.providerTerritory : (java.lang.CharSequence) defaultValue(fields()[9]);
        if (dataBuilder != null) {
          try {
            record.data = this.dataBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("data"));
            throw e;
          }
        } else {
          record.data = fieldSetFlags()[10] ? this.data : (data) defaultValue(fields()[10]);
        }
        record.id = fieldSetFlags()[11] ? this.id : (java.lang.CharSequence) defaultValue(fields()[11]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OogwayProfileCreated>
    WRITER$ = (org.apache.avro.io.DatumWriter<OogwayProfileCreated>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OogwayProfileCreated>
    READER$ = (org.apache.avro.io.DatumReader<OogwayProfileCreated>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.origin);

    out.writeString(this.activityType);

    out.writeString(this.event);

    out.writeString(this.householdId);

    out.writeString(this.originatingSystem);

    out.writeString(this.provider);

    if (this.proposition == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.proposition);
    }

    out.writeString(this.activityTimestamp);

    out.writeString(this.profileId);

    out.writeString(this.providerTerritory);

    this.data.customEncode(out);

    out.writeString(this.id);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.origin = in.readString(this.origin instanceof Utf8 ? (Utf8)this.origin : null);

      this.activityType = in.readString(this.activityType instanceof Utf8 ? (Utf8)this.activityType : null);

      this.event = in.readString(this.event instanceof Utf8 ? (Utf8)this.event : null);

      this.householdId = in.readString(this.householdId instanceof Utf8 ? (Utf8)this.householdId : null);

      this.originatingSystem = in.readString(this.originatingSystem instanceof Utf8 ? (Utf8)this.originatingSystem : null);

      this.provider = in.readString(this.provider instanceof Utf8 ? (Utf8)this.provider : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.proposition = null;
      } else {
        this.proposition = in.readString(this.proposition instanceof Utf8 ? (Utf8)this.proposition : null);
      }

      this.activityTimestamp = in.readString(this.activityTimestamp instanceof Utf8 ? (Utf8)this.activityTimestamp : null);

      this.profileId = in.readString(this.profileId instanceof Utf8 ? (Utf8)this.profileId : null);

      this.providerTerritory = in.readString(this.providerTerritory instanceof Utf8 ? (Utf8)this.providerTerritory : null);

      if (this.data == null) {
        this.data = new data();
      }
      this.data.customDecode(in);

      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

    } else {
      for (int i = 0; i < 12; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.origin = in.readString(this.origin instanceof Utf8 ? (Utf8)this.origin : null);
          break;

        case 1:
          this.activityType = in.readString(this.activityType instanceof Utf8 ? (Utf8)this.activityType : null);
          break;

        case 2:
          this.event = in.readString(this.event instanceof Utf8 ? (Utf8)this.event : null);
          break;

        case 3:
          this.householdId = in.readString(this.householdId instanceof Utf8 ? (Utf8)this.householdId : null);
          break;

        case 4:
          this.originatingSystem = in.readString(this.originatingSystem instanceof Utf8 ? (Utf8)this.originatingSystem : null);
          break;

        case 5:
          this.provider = in.readString(this.provider instanceof Utf8 ? (Utf8)this.provider : null);
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.proposition = null;
          } else {
            this.proposition = in.readString(this.proposition instanceof Utf8 ? (Utf8)this.proposition : null);
          }
          break;

        case 7:
          this.activityTimestamp = in.readString(this.activityTimestamp instanceof Utf8 ? (Utf8)this.activityTimestamp : null);
          break;

        case 8:
          this.profileId = in.readString(this.profileId instanceof Utf8 ? (Utf8)this.profileId : null);
          break;

        case 9:
          this.providerTerritory = in.readString(this.providerTerritory instanceof Utf8 ? (Utf8)this.providerTerritory : null);
          break;

        case 10:
          if (this.data == null) {
            this.data = new data();
          }
          this.data.customDecode(in);
          break;

        case 11:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










